# Generated by Django 6.0.5 on 2026-06-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="special_guests",
        ),
        migrations.AddField(
            model_name="booking",
            name="special_requests",
            field=models.TextField(blank=True),
        ),
    ]
