# Generated by Django 6.0.6 on 2026-07-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_booking_special_guests_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInquiry',
        ),
    ]
